Sinatra メモアプリ
e6i24vi/sinatra_practice pull request #1
Opened 2022-07-10 10:10 UTC by e6i24vi

2022-07-15 06:33 UTC, func09 requested changes
Rubocopを通っていないコードが多いみたいなので
まずは通るようにしてから再提出お願いします〜

2022-07-15 06:33 UTC, func09 commented on app.rb
> +$memos_file = 'json/memos.json'
変数名のプレフィックスに `$` を使った理由はなんででしょうか？

2022-07-15 06:33 UTC, func09 commented on app.rb
> +  JSON.load(memo)
`JSON.load` は rubocop に Security/JSONLoad 違反が出るので `JSON.parse` にしましょう。

2022-07-15 06:33 UTC, func09 commented on app.rb
> +post '/memos/create' do
REST的なURLにするのであれば `POST /memos` だけで OKですね。 `create` は取ってしまいましょう。

2022-07-18 08:50 UTC, e6i24vi commented on app.rb
> +$memos_file = 'json/memos.json'
グローバル変数を用いて、変数を管理したかったからです。

2022-07-18 08:50 UTC, e6i24vi commented on app.rb
> +post '/memos/create' do
済
わかりました。

2022-07-18 10:29 UTC, func09 commented on app.rb
> +$memos_file = 'json/memos.json'
リクエストスコープからローカル変数変数を参照できるのでグローバル変数にする必要がなさそうです。
という話をしたかったのですが、言葉足らずでした 🙏

2022-07-18 10:47 UTC, func09 reviewed
> fileとの受け渡しが多くなる方法になってしまいました。何か少し違うような

主にmax_idの保持と参照でコードが複雑になっているので
そこを修正するともっと良くなって、次のDB版にも引き継ぎやすくなると思います 😄

2022-07-18 10:47 UTC, func09 commented on app.rb
> +require 'json'
このファイルで `JSON` クラスを使っていないので消して良さそうです

2022-07-18 10:47 UTC, func09 commented on app.rb
> +  Data.print_idmax(id_max.to_s)
indexの繰り上げで、処理が多くなってしまっていますね。
このままでも良いと思うのですが、テキストファイルに書き込む処理を無くして

```ruby
next_id =  (@memos.map{|memo| memo['id'].to_i}.max || 0) + 1
```

こんな感じで、ファイルからIDの最大値を取得して 1 追加してあげればシンプルになるかなと思いました。

2022-07-18 10:47 UTC, func09 commented on db/database.rb
> +      file.write(id_max.to_s)
ファイルを読み込むたびに `id_max` を書き込むのは効率がよくないですね。
上のコメントを参考にして、`id_max` を記録するという処理を無くしてしまっても良いと思います。

2022-07-18 13:12 UTC, e6i24vi commented on app.rb
> +require 'json'
済
消しました。

2022-07-18 13:13 UTC, e6i24vi commented on app.rb
> +  Data.print_idmax(id_max.to_s)
済
確かに、そうですね。何を悩んでいたのか

2022-07-18 13:13 UTC, e6i24vi commented on db/database.rb
> +      file.write(id_max.to_s)
済
同上

2022-07-19 07:23 UTC, func09 approved these changes
LGTMです〜 🎉

2022-07-19 07:23 UTC, func09 commented on app.rb
> +  memos << { 'id' => next_id.to_s, 'title' => h(params[:title]).to_s, 'content' => h(params[:content]).to_s }
👍

2022-07-23 05:32 UTC, merged